version = "2.7.5"
maxColumn = 120
assumeStandardLibraryStripMargin = true

style = defaultWithAlign

align = some
align.openParenCallSite = false
align.openParenDefnSite = false
align.arrowEnumeratorGenerator = false
newlines.alwaysBeforeTopLevelStatements = true
newlines.sometimesBeforeColonInMethodReturnType = true
newlines.penalizeSingleSelectMultiArgList = true


includeCurlyBraceInSelectChains = true
danglingParentheses = true

rewrite {
  rules = [AvoidInfix, SortImports, RedundantParens, SortModifiers, PreferCurlyFors]
  redundantBraces.stringInterpolation = true
}
